import { Restaurant, Category } from '@/types';

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'all',
    name: 'All',
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=200&q=80',
  },
  {
    id: 'thali',
    name: 'Thali',
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=200&q=80',
  },
  {
    id: 'kathiyawadi',
    name: 'Kathiyawadi',
    image: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?auto=format&fit=crop&w=200&q=80',
  },
  {
    id: 'indian',
    name: 'Punjabi',
    image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=200&q=80',
  },
  {
    id: 'chinese',
    name: 'Chinese',
    image: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?auto=format&fit=crop&w=200&q=80',
  },
  {
    id: 'desserts',
    name: 'Sweets',
    image: 'https://images.unsplash.com/photo-1589135306090-e177fc33b948?auto=format&fit=crop&w=200&q=80',
  },
  {
    id: 'southindian',
    name: 'South Indian',
    image: 'https://images.unsplash.com/photo-1541832676-9b763b0239ab?auto=format&fit=crop&w=200&q=80',
  },
  {
    id: 'healthy',
    name: 'Snacks',
    image: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?auto=format&fit=crop&w=200&q=80',
  },
];

export const MOCK_RESTAURANTS: Restaurant[] = [
  // ── PATAN HOTELS ──
  {
    id: 'rest-1',
    name: 'Hotel Asopalav',
    image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80',
    cuisines: ['Gujarati Thali', 'Punjabi', 'North Indian', 'Hotel', 'Kathiyawadi'],
    rating: 4.5,
    deliveryTime: 20,
    distance: 1.1,
    priceForTwo: 350,
    isFeatured: true,
    offer: '40% OFF up to ₹80',
    address: 'Station Road, Chanasma Highway, Patan, Gujarat',
    category: 'thali',
    menu: [
      {
        id: 'm1-1',
        name: 'Executive Gujarati Thali',
        description: '3 Veg Sabji, 4 Roti/Puri, Dal, Kadhi, Rice, Butter Milk, Papad, Pickle and 1 Sweet.',
        price: 190,
        image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=400&q=80',
        isVeg: true,
        isBestseller: true,
        category: 'Thali',
      },
      {
        id: 'm1-2',
        name: 'Paneer Butter Masala',
        description: 'Fresh paneer cubes cooked in a rich, buttery, creamy tomato onion gravy.',
        price: 210,
        image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=400&q=80',
        isVeg: true,
        isBestseller: true,
        category: 'Punjabi',
      },
    ],
  },
  {
    id: 'rest-2',
    name: 'Bansi Kathiyawadi',
    image: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?auto=format&fit=crop&w=800&q=80',
    cuisines: ['Kathiyawadi', 'Gujarati', 'Desi Ghee Items', 'Hotel', 'Highway'],
    rating: 4.6,
    deliveryTime: 25,
    distance: 1.8,
    priceForTwo: 240,
    isFeatured: true,
    offer: 'Free Chaas with Thali',
    address: 'Unjha-Mehsana Highway, Industrial Area, Unjha, Gujarat - 384170',
    category: 'kathiyawadi',
    menu: [
      {
        id: 'm2-1',
        name: 'Ringan No Oro (Baingan Bharta)',
        description: 'Traditional charcoal-roasted eggplant mashed and cooked with spring onions and Gujarati spices.',
        price: 130,
        image: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?auto=format&fit=crop&w=400&q=80',
        isVeg: true,
        isBestseller: true,
        category: 'Kathiyawadi',
      },
    ],
  },
  {
    id: 'rest-3',
    name: 'Hotel The Grand Piano',
    image: 'https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=800&q=80',
    cuisines: ['Multi-Cuisine', 'Punjabi', 'Hotel', 'Premium Dining'],
    rating: 4.7,
    deliveryTime: 22,
    distance: 1.5,
    priceForTwo: 500,
    isFeatured: true,
    offer: 'Free Dessert on ₹499+',
    address: 'Siddhpur Char Rasta, Patan, Gujarat',
    category: 'indian',
    menu: [
      {
        id: 'm3-1',
        name: 'Kaju Curry Premium',
        description: 'Roasted cashew nuts simmered in rich, sweet, and creamy golden gravy.',
        price: 240,
        image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=400&q=80',
        isVeg: true,
        isBestseller: true,
        category: 'Punjabi',
      },
    ],
  },
  {
    id: 'rest-4',
    name: 'Hotel Navjivan',
    image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=800&q=80',
    cuisines: ['Gujarati Thali', 'Punjabi', 'Hotel', 'South Indian'],
    rating: 4.4,
    deliveryTime: 18,
    distance: 0.9,
    priceForTwo: 300,
    isFeatured: true,
    offer: '20% OFF on ₹299+',
    address: 'Near Railway Station Road, Patan, Gujarat',
    category: 'thali',
    menu: [
      {
        id: 'm4-1',
        name: 'Navjivan Unlimited Special Thali',
        description: 'A traditional feast of curries, rotli, special dal-kadhi, farsan, shrikhand, and unlimited buttermilk.',
        price: 199,
        image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=400&q=80',
        isVeg: true,
        isBestseller: true,
        category: 'Thali',
      },
    ],
  },
  {
    id: 'rest-5',
    name: 'Tulsi Restaurant',
    image: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=800&q=80',
    cuisines: ['North Indian', 'Punjabi', 'Chinese', 'Hotel'],
    rating: 4.3,
    deliveryTime: 20,
    distance: 1.2,
    priceForTwo: 300,
    address: 'Near New District Court, Patan, Gujarat',
    category: 'indian',
    menu: [
      {
        id: 'm5-1',
        name: 'Paneer Kadai',
        description: 'Paneer tossed with bell peppers and freshly ground spices in a kadai.',
        price: 190,
        image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=400&q=80',
        isVeg: true,
        isBestseller: true,
        category: 'Punjabi',
      },
    ],
  },
  {
    id: 'rest-6',
    name: 'The Secret Kitchen',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80',
    cuisines: ['Continental', 'Sweets', 'Mocktails', 'Hotel'],
    rating: 4.5,
    deliveryTime: 30,
    distance: 2.1,
    priceForTwo: 600,
    address: 'Netaji Road, Patan, Gujarat',
    category: 'desserts',
    menu: [
      {
        id: 'm6-1',
        name: 'Kesar Pista Shrikhand',
        description: 'Creamy yogurt dessert sweetened with saffron, cardamom, and garnished with premium nuts.',
        price: 120,
        image: 'https://images.unsplash.com/photo-1589135306090-e177fc33b948?auto=format&fit=crop&w=400&q=80',
        isVeg: true,
        isBestseller: true,
        category: 'Sweets',
      },
    ],
  },
  {
    id: 'rest-7',
    name: 'The Grand Raveta',
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=800&q=80',
    cuisines: ['Punjabi', 'Fast Food', 'Hotel'],
    rating: 4.1,
    deliveryTime: 25,
    distance: 2.3,
    priceForTwo: 350,
    address: 'University Road, Patan, Gujarat',
    category: 'indian',
    menu: [
      {
        id: 'm7-1',
        name: 'Veg Handi Curry',
        description: 'Seasonal mix vegetables slow cooked in a special handi gravy.',
        price: 160,
        image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=400&q=80',
        isVeg: true,
        category: 'Punjabi',
      },
    ],
  },
  {
    id: 'rest-8',
    name: 'Neelam Restaurant & Banquets',
    image: 'https://images.unsplash.com/photo-1541832676-9b763b0239ab?auto=format&fit=crop&w=800&q=80',
    cuisines: ['South Indian', 'Fast Food', 'Hotel'],
    rating: 4.3,
    deliveryTime: 28,
    distance: 2.2,
    priceForTwo: 280,
    address: 'GIDC Area, Patan, Gujarat',
    category: 'southindian',
    menu: [
      {
        id: 'm8-1',
        name: 'Mysore Masala Dosa',
        description: 'Crispy rice crepe spread with spicy garlic chutney, filled with potato bhaji, served with sambar.',
        price: 140,
        image: 'https://images.unsplash.com/photo-1541832676-9b763b0239ab?auto=format&fit=crop&w=400&q=80',
        isVeg: true,
        isBestseller: true,
        category: 'South Indian',
      },
    ],
  },

  // ── UNJHA HOTELS (HIGHWAY FOCUSSED) ──
  {
    id: 'rest-9',
    name: 'Hotel Caravan',
    image: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=800&q=80',
    cuisines: ['Punjabi', 'Gujarati', 'Fast Food', 'Hotel', 'Highway'],
    rating: 4.4,
    deliveryTime: 24,
    distance: 1.2,
    priceForTwo: 350,
    isFeatured: true,
    offer: 'Free Dessert on ₹499+',
    address: 'Mehsana-Unjha Highway, Unjha, Gujarat - 384170',
    category: 'indian',
    menu: [
      {
        id: 'm9-1',
        name: 'Paneer Tikka Masala',
        description: 'Tandoori paneer tikkas cooked in a spicy, onion-tomato masala gravy.',
        price: 230,
        image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=400&q=80',
        isVeg: true,
        isBestseller: true,
        category: 'Punjabi',
      },
    ],
  },
  {
    id: 'rest-10',
    name: 'Hotel Comfy & Restaurant',
    image: 'https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=800&q=80',
    cuisines: ['Punjabi', 'Chinese', 'Hotel', 'Highway', 'Family Dining'],
    rating: 4.5,
    deliveryTime: 20,
    distance: 1.6,
    priceForTwo: 400,
    isFeatured: true,
    offer: 'Buy 2 Get 1 Free Mocktails',
    address: 'Unjha-Mehsana Highway, Unava, Gujarat - 384160',
    category: 'indian',
    menu: [
      {
        id: 'm10-1',
        name: 'Veg Sizzler',
        description: 'Hot sizzling platter loaded with cutlets, stir-fried vegetables, french fries, and signature brown sauce.',
        price: 280,
        image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=400&q=80',
        isVeg: true,
        isBestseller: true,
        category: 'Punjabi',
      },
    ],
  },
  {
    id: 'rest-11',
    name: 'Hotel Decent',
    image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80',
    cuisines: ['Gujarati Thali', 'Punjabi', 'Hotel', 'Highway'],
    rating: 3.8,
    deliveryTime: 22,
    distance: 1.9,
    priceForTwo: 280,
    address: 'Unjha-Mehsana Highway Road, near Gunj Bazar, Unava, Gujarat - 384160',
    category: 'thali',
    menu: [
      {
        id: 'm11-1',
        name: 'Decent Special Gujarati Thali',
        description: 'Traditional home style thin rotis served with 3 seasonal sabjis, kadhi, khichdi, papad and fresh buttermilk.',
        price: 150,
        image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=400&q=80',
        isVeg: true,
        category: 'Thali',
      },
    ],
  },
  {
    id: 'rest-12',
    name: 'Hotel Sahyog',
    image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=800&q=80',
    cuisines: ['Punjabi', 'Chinese', 'Hotel', 'Highway'],
    rating: 4.1,
    deliveryTime: 25,
    distance: 2.7,
    priceForTwo: 320,
    address: 'Mehsana-Unjha Highway, near Gita IOC Pump, Bhandu, Gujarat - 384120',
    category: 'indian',
    menu: [
      {
        id: 'm12-1',
        name: 'Kaju Curry Sahyog Special',
        description: 'Rich creamy cashew gravy cooked with traditional highway dhaba spice recipes.',
        price: 210,
        image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=400&q=80',
        isVeg: true,
        isBestseller: true,
        category: 'Punjabi',
      },
    ],
  },
  {
    id: 'rest-13',
    name: 'Shyam Restaurant',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80',
    cuisines: ['Punjabi', 'Gujarati', 'South Indian', 'Highway'],
    rating: 4.2,
    deliveryTime: 23,
    distance: 2.1,
    priceForTwo: 300,
    address: 'Mehsana-Unjha Highway Bypass, Unjha, Gujarat - 384170',
    category: 'thali',
    menu: [
      {
        id: 'm13-1',
        name: 'Unlimited Gujarati Fix Thali',
        description: 'Complete meal containing roti, subji, dal, rice, papad, and butter milk.',
        price: 140,
        image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=400&q=80',
        isVeg: true,
        isBestseller: true,
        category: 'Thali',
      },
    ],
  },
  {
    id: 'rest-14',
    name: 'Piplaj Dal Bati Restaurant',
    image: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?auto=format&fit=crop&w=800&q=80',
    cuisines: ['Rajasthani', 'Dal Bati', 'Hotel', 'Highway'],
    rating: 4.4,
    deliveryTime: 26,
    distance: 3.5,
    priceForTwo: 300,
    address: 'Mehsana-Unjha Highway, near Khari River, Bhandu, Gujarat - 384120',
    category: 'kathiyawadi',
    menu: [
      {
        id: 'm14-1',
        name: 'Special Dal Bati Platter',
        description: '4 Ghee loaded batis served with special garlic spicy dal, churma, garlic chutney, and onion salad.',
        price: 170,
        image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=400&q=80',
        isVeg: true,
        isBestseller: true,
        category: 'Kathiyawadi',
      },
    ],
  },
  {
    id: 'rest-15',
    name: 'Sahara Hotel',
    image: 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?auto=format&fit=crop&w=800&q=80',
    cuisines: ['Punjabi', 'North Indian', 'Hotel', 'Highway'],
    rating: 3.6,
    deliveryTime: 30,
    distance: 3.1,
    priceForTwo: 300,
    address: 'Palanpur-Unjha Highway, Maktupur, Unjha, Gujarat - 384170',
    category: 'indian',
    menu: [
      {
        id: 'm15-1',
        name: 'Mix Veg Curry',
        description: 'Dry preparation of seasonal fresh vegetables cooked with basic dry spices.',
        price: 150,
        image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=400&q=80',
        isVeg: true,
        category: 'Punjabi',
      },
    ],
  },
  {
    id: 'rest-16',
    name: 'Umiya Mataji Bhojanalaya',
    image: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=800&q=80',
    cuisines: ['Gujarati Thali', 'Kathiyawadi', 'Hotel', 'Temple Food'],
    rating: 4.7,
    deliveryTime: 15,
    distance: 0.5,
    priceForTwo: 140,
    address: 'Gunj Bazar, Unjha, Gujarat - 384170',
    category: 'thali',
    menu: [
      {
        id: 'm16-1',
        name: 'Prasadi Unlimited Gujarati Thali',
        description: 'Traditional simple and pure satvik meal made with pure ghee and local farm ingredients.',
        price: 70,
        image: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=400&q=80',
        isVeg: true,
        isBestseller: true,
        category: 'Thali',
      },
    ],
  },
  {
    id: 'rest-17',
    name: 'New Jagir Hotel',
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80',
    cuisines: ['Chinese', 'Punjabi', 'South Indian', 'Hotel', 'Gujarati', 'Kathiyawadi'],
    rating: 4.0,
    deliveryTime: 20,
    distance: 0.8,
    priceForTwo: 300,
    address: 'Near APMC Gate 1, Main Road, Unjha, Gujarat - 384170',
    category: 'thali',
    menu: [
      {
        id: 'm17-1',
        name: 'Premium Gujarati Thali',
        description: 'Delicious thali containing multiple vegetables, sweet, puri, rotli, dal-rice and buttermilk.',
        price: 150,
        image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=400&q=80',
        isVeg: true,
        isBestseller: true,
        category: 'Thali',
      },
    ],
  },
  {
    id: 'rest-18',
    name: 'Pruthvi Garden Restaurant',
    image: 'https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=800&q=80',
    cuisines: ['Punjabi', 'Chinese', 'Fast Food', 'Hotel'],
    rating: 4.1,
    deliveryTime: 28,
    distance: 1.9,
    priceForTwo: 400,
    address: 'Opposite Jagir Da Dhaba, Shambu Park Society, Unjha, Gujarat - 384170',
    category: 'indian',
    menu: [
      {
        id: 'm18-1',
        name: 'Veg Crispy',
        description: 'Crispy deep-fried vegetables tossed in hot garlic sauce.',
        price: 150,
        image: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?auto=format&fit=crop&w=400&q=80',
        isVeg: true,
        category: 'Chinese',
      },
    ],
  },
  {
    id: 'rest-19',
    name: 'Gau Gamathi Kathiyawadi Restaurant',
    image: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?auto=format&fit=crop&w=800&q=80',
    cuisines: ['Kathiyawadi', 'Gujarati', 'Hotel'],
    rating: 4.3,
    deliveryTime: 22,
    distance: 1.3,
    priceForTwo: 250,
    address: 'Near APMC Market, Unava, Gunj Bazar, Unjha, Gujarat - 384170',
    category: 'kathiyawadi',
    menu: [
      {
        id: 'm19-1',
        name: 'Lasaniya Bataka Shaak',
        description: 'Spicy baby potatoes slow cooked in rich garlic and Kathiyawadi masala gravy.',
        price: 110,
        image: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?auto=format&fit=crop&w=400&q=80',
        isVeg: true,
        isBestseller: true,
        category: 'Kathiyawadi',
      },
    ],
  },
  {
    id: 'rest-20',
    name: 'Food Post Restaurant',
    image: 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?auto=format&fit=crop&w=800&q=80',
    cuisines: ['Chinese', 'Gujarati', 'North Indian', 'Hotel'],
    rating: 4.2,
    deliveryTime: 23,
    distance: 1.1,
    priceForTwo: 350,
    address: 'Opposite Suvidha Hospital, BOB Bank Lane, Gunj Bazar, Unjha, Gujarat - 384170',
    category: 'chinese',
    menu: [
      {
        id: 'm20-1',
        name: 'Paneer Manchurian Dry',
        description: 'Fried cottage cheese cubes tossed with onion, garlic, green chillies and soy sauce.',
        price: 180,
        image: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?auto=format&fit=crop&w=400&q=80',
        isVeg: true,
        isBestseller: true,
        category: 'Chinese',
      },
    ],
  },

  // ── PATAN RESTAURANTS (ZOMATO REFERENCE) ──
  {
    id: 'rest-21',
    name: "Domino's Pizza",
    image: 'https://b.zmtcdn.com/data/pictures/8/20989678/538e8379e055d995d78b3ccf19af665b_o2_featured_v2.jpg',
    cuisines: ['Pizza', 'Fast Food'],
    rating: 3.9,
    deliveryTime: 30,
    distance: 1.4,
    priceForTwo: 400,
    address: 'Shop 24-28, Ground Floor, Shiv Arcade, Block B, Patan Locality, Patan',
    category: 'chinese',
    menu: [
      {
        id: 'm21-1',
        name: 'Veg Farmhouse Pizza',
        description: 'Loaded with capsicum, mushroom, onion, tomato and golden corn on a hand-tossed base.',
        price: 320,
        image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=400&q=80',
        isVeg: true,
        isBestseller: true,
        category: 'Pizza',
      },
    ],
  },
  {
    id: 'rest-22',
    name: "La Pino'z Pizza",
    image: 'https://b.zmtcdn.com/data/pictures/chains/6/19901876/54b6de34323395a3b10897e48bd2a6e5_o2_featured_v2.jpg',
    cuisines: ['Pizza', 'Italian', 'Pasta'],
    rating: 4.1,
    deliveryTime: 28,
    distance: 1.6,
    priceForTwo: 450,
    isFeatured: true,
    offer: '20% OFF on ₹499+',
    address: 'G-15/16, Krishnam Skyline, Near Padmanash Chokdi, Patan-Chanasma Highway, Patan',
    category: 'chinese',
    menu: [
      {
        id: 'm22-1',
        name: 'Peri Peri Paneer Pizza',
        description: 'Spicy peri-peri sauce with fresh paneer and roasted peppers on a crispy base.',
        price: 299,
        image: 'https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?auto=format&fit=crop&w=400&q=80',
        isVeg: true,
        isBestseller: true,
        category: 'Pizza',
      },
    ],
  },
  {
    id: 'rest-23',
    name: '9 To 69 Cafe',
    image: 'https://b.zmtcdn.com/data/pictures/6/22372356/11dafd9de6a980152bc1511dbfba2cdc_o2_featured_v2.jpg',
    cuisines: ['North Indian', 'Korean', 'Burger', 'Cafe'],
    rating: 3.5,
    deliveryTime: 25,
    distance: 1.2,
    priceForTwo: 350,
    address: '5, Shop 82A, A Square Complex, LP Bhavan, Siddhpur Road, Patan Locality, Patan',
    category: 'chinese',
    menu: [
      {
        id: 'm23-1',
        name: 'Veg Loaded Burger',
        description: 'Crispy fried veggie patty with cheese, lettuce, pickles, and chipotle sauce.',
        price: 150,
        image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=400&q=80',
        isVeg: true,
        category: 'Burger',
      },
    ],
  },
  {
    id: 'rest-24',
    name: 'Dwarkadhish Bhajipav',
    image: 'https://b.zmtcdn.com/data/pictures/5/22264575/ebdb002168c72d3a657843bc9cc57dfc_o2_featured_v2.jpg',
    cuisines: ['Street Food', 'North Indian', 'Fast Food'],
    rating: 4.0,
    deliveryTime: 15,
    distance: 0.6,
    priceForTwo: 100,
    address: 'Jalaram Chowk, Patan Locality, Patan, Gujarat',
    category: 'healthy',
    menu: [
      {
        id: 'm24-1',
        name: 'Special Pav Bhaji',
        description: 'Mashed spiced vegetables served with buttered pav, lemon, onion and coriander.',
        price: 60,
        image: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?auto=format&fit=crop&w=400&q=80',
        isVeg: true,
        isBestseller: true,
        category: 'Street Food',
      },
    ],
  },
  {
    id: 'rest-25',
    name: 'Chai Tapri',
    image: 'https://b.zmtcdn.com/data/pictures/9/22502909/c0339fb94c965e2e88126eb75e416c84_o2_featured_v2.jpg',
    cuisines: ['Tea', 'Fast Food', 'Street Food', 'Snacks'],
    rating: 4.0,
    deliveryTime: 12,
    distance: 0.8,
    priceForTwo: 80,
    address: 'Shop G-38, Keshar Green Complex, Near Sudama Chokdi, Patan Locality, Patan',
    category: 'healthy',
    menu: [
      {
        id: 'm25-1',
        name: 'Masala Cutting Chai',
        description: 'Strong ginger-cardamom tea brewed with full milk and house spice blend.',
        price: 15,
        image: 'https://images.unsplash.com/photo-1571934811356-5cc061b6821f?auto=format&fit=crop&w=400&q=80',
        isVeg: true,
        isBestseller: true,
        category: 'Tea',
      },
    ],
  },
  {
    id: 'rest-26',
    name: 'Vadilal Ice Creams',
    image: 'https://b.zmtcdn.com/data/pictures/2/20767642/e1a8569e414c5535da0b359eb37ec3ab_o2_featured_v2.jpg',
    cuisines: ['Ice Cream', 'Desserts', 'Sweets'],
    rating: 4.0,
    deliveryTime: 18,
    distance: 0.9,
    priceForTwo: 150,
    address: '203-204, Tirupati Bazar, Siddhpur Char Rasta, Near Vijay Cinema, Patan Locality, Patan',
    category: 'desserts',
    menu: [
      {
        id: 'm26-1',
        name: 'Kesar Pista Sundae',
        description: 'Rich saffron and pistachio ice cream topped with dry fruits and rose syrup.',
        price: 80,
        image: 'https://images.unsplash.com/photo-1554520735-0a6b8b6ce8b7?auto=format&fit=crop&w=400&q=80',
        isVeg: true,
        isBestseller: true,
        category: 'Ice Cream',
      },
    ],
  },
  {
    id: 'rest-27',
    name: 'Only Dosa House',
    image: 'https://b.zmtcdn.com/data/pictures/0/21832020/94b289f2d0d84a5c640d6c968ed89d81_o2_featured_v2.jpg',
    cuisines: ['South Indian', 'Street Food', 'Dosa'],
    rating: 4.0,
    deliveryTime: 20,
    distance: 1.0,
    priceForTwo: 150,
    address: '15/12/191, Near Shakuntal Green Society, Sudama Cross Road, Patan Locality, Patan',
    category: 'southindian',
    menu: [
      {
        id: 'm27-1',
        name: 'Paper Masala Dosa',
        description: 'Super-thin crispy dosa filled with spiced potato masala, served with sambar and chutneys.',
        price: 90,
        image: 'https://images.unsplash.com/photo-1541832676-9b763b0239ab?auto=format&fit=crop&w=400&q=80',
        isVeg: true,
        isBestseller: true,
        category: 'South Indian',
      },
    ],
  },
  {
    id: 'rest-28',
    name: 'Annadhara Gujarati Thal',
    image: 'https://b.zmtcdn.com/data/pictures/3/22656293/93c20f0ad7230aa2ec9fab61dd8a702d_o2_featured_v2.jpg',
    cuisines: ['Gujarati', 'Thali', 'Beverages'],
    rating: 4.2,
    deliveryTime: 22,
    distance: 1.3,
    priceForTwo: 220,
    isFeatured: true,
    offer: 'Unlimited Thali ₹149',
    address: 'Shop F 113-119, Krishum Sky Line Complex, Chanasma Highway, Near Croma, Patan Locality, Patan',
    category: 'thali',
    menu: [
      {
        id: 'm28-1',
        name: 'Annadhara Unlimited Gujarati Thal',
        description: 'Complete Gujarati meal — seasonal subji, dal, kadhi, rice, rotli, puri, papad, pickle, and meetha.',
        price: 149,
        image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=400&q=80',
        isVeg: true,
        isBestseller: true,
        category: 'Thali',
      },
    ],
  },
  {
    id: 'rest-29',
    name: "Mumma's Kitchen",
    image: 'https://b.zmtcdn.com/data/pictures/6/22633176/f947508872395ebea7a2a491cd51e7af_o2_featured_v2.jpg',
    cuisines: ['Gujarati', 'Street Food', 'Home Style'],
    rating: 3.7,
    deliveryTime: 25,
    distance: 1.5,
    priceForTwo: 180,
    address: 'F-23, 1st Floor, Mangalam Square, Opposite Sadbhav Hospital, Patan Locality, Patan',
    category: 'thali',
    menu: [
      {
        id: 'm29-1',
        name: 'Home Style Gujarati Thali',
        description: 'Lovingly prepared home-style meal with seasonal sabji, dal, chaas, and rotli.',
        price: 90,
        image: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=400&q=80',
        isVeg: true,
        isBestseller: true,
        category: 'Thali',
      },
    ],
  },
];
